# Generated by Django 4.0.5 on 2022-08-22 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=200)),
                ('coast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='topics/%Y_%m_%s/')),
                ('topic_id', models.SlugField(max_length=350)),
                ('code_field', models.TextField(blank=True)),
                ('Youtube_Link ', embed_video.fields.EmbedVideoField(blank=True)),
                ('category', models.ManyToManyField(blank=True, related_name='category', to='Courses.category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag', to='Courses.tag')),
            ],
        ),
    ]
