# Generated by Django 4.0.5 on 2022-09-22 13:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='contents',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
