# Generated by Django 4.0.5 on 2022-09-26 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_alter_topic_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='code_field',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_id',
        ),
    ]
