# Generated by Django 4.0.5 on 2022-09-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_remove_topic_code_field_remove_topic_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='Youtube_Link ',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tag',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='courses', to='Courses.category'),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='topic', to='Courses.category'),
        ),
    ]
